# Generated by Codex on 2026-03-17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_systemprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voice_id', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='voice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.voice'),
        ),
        migrations.RenameField(
            model_name='systemprompt',
            old_name='old_number',
            new_name='order_number',
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='prompt',
            field=models.TextField(max_length=10000),
        ),
    ]
