# Generated by Django 6.0.1 on 2026-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_default_voice"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="memory_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="request_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="input",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="output",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="user_message",
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("friend", "request_id"), name="unique_friend_chat_request"
            ),
        ),
    ]
