# Generated by Django 6.0.1 on 2026-10-10 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def preserve_existing(apps, schema_editor):
    Character = apps.get_model('web', 'Character')
    Friend = apps.get_model('web', 'Friend')
    Message = apps.get_model('web', 'Message')
    for character in Character.objects.all().iterator():
        character.public_description = character.profile[:200]
        character.persona_prompt = character.profile
        character.save(update_fields=['public_description', 'persona_prompt'])
    from django.db.models import Count
    for group in Friend.objects.values('me_id', 'character_id').annotate(total=Count('id')).filter(total__gt=1):
        friends = list(Friend.objects.filter(me_id=group['me_id'], character_id=group['character_id']).order_by('id'))
        keeper = friends[0]
        for duplicate in friends[1:]:
            # Request IDs are unique per old relationship; remove only a colliding
            # identifier, never its message content.
            for message in Message.objects.filter(friend=duplicate):
                if message.request_id and Message.objects.filter(friend=keeper, request_id=message.request_id).exists():
                    message.request_id = None
                message.friend = keeper
                message.save(update_fields=['friend', 'request_id'])
            if duplicate.memory:
                keeper.memory = ((keeper.memory or '')+'\n'+duplicate.memory)[:5000]
                keeper.save(update_fields=['memory'])
            duplicate.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_friendly_voice_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("object_id", models.PositiveIntegerField()),
                ("detail", models.CharField(blank=True, max_length=200)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("object_id", models.PositiveIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("dedupe_key", models.CharField(max_length=100, unique=True)),
                ("status", models.CharField(default="queued", max_length=12)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("sha256", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("status", models.CharField(default="uploaded", max_length=12)),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("resolved", "已处理"),
                            ("rejected", "不成立"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("resolution", models.CharField(blank=True, max_length=500)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="persona_prompt",
            field=models.TextField(blank=True, max_length=100000),
        ),
        migrations.AddField(
            model_name="character",
            name="public_description",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="character",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("published", "已发布"),
                    ("archived", "已归档"),
                ],
                default="published",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="character",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "仅自己"),
                    ("unlisted", "不在发现页展示"),
                    ("public", "公开"),
                ],
                default="public",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="friend",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="friend",
            name="memory_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="message",
            name="audio",
            field=models.FileField(blank=True, upload_to="chat/audio/"),
        ),
        migrations.AddField(
            model_name="message",
            name="error",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(default="completed", max_length=12),
        ),
        migrations.AddField(
            model_name="voice",
            name="error",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="voice",
            name="kind",
            field=models.CharField(default="preset", max_length=10),
        ),
        migrations.AddField(
            model_name="voice",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="voice",
            name="status",
            field=models.CharField(default="ready", max_length=12),
        ),
        migrations.AddField(
            model_name="voice",
            name="target_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="character",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.voice",
            ),
        ),
        migrations.RunPython(preserve_existing, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(
                fields=("me", "character"), name="unique_user_character_friend"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.character"
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="knowledgechunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="web.knowledgedocument",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.character"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.userprofile"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgedocument",
            constraint=models.UniqueConstraint(
                fields=("character", "sha256"), name="unique_character_document"
            ),
        ),
    ]
