# Generated by Django 6.0.1 on 2026-10-10 14:43

import django.db.models.deletion
import web.services.private_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_product_lifecycle_resources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="audio",
            field=models.FileField(
                blank=True,
                storage=web.services.private_files.private_storage,
                upload_to="chat/audio/",
            ),
        ),
        migrations.CreateModel(
            name="GenerationLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=64)),
                ("cancelled", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                (
                    "friend",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="web.friend"
                    ),
                ),
            ],
        ),
    ]
