# Generated by Django 6.0.1 on 2026-10-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_shared_generation_and_private_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
