# Generated by Django 6.0.1 on 2026-10-10 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_persisted_knowledge_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=20)),
                ("success", models.BooleanField()),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="knowledgechunk",
            name="vector",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="index_mode",
            field=models.CharField(default="keyword", max_length=20),
        ),
    ]
