# Generated by Django 6.0.1 on 2026-10-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_knowledge_vectors_and_service_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="moderation_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="character",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("reviewing", "待审核"),
                    ("rejected", "审核拒绝"),
                    ("published", "已发布"),
                    ("archived", "已归档"),
                ],
                default="published",
                max_length=12,
            ),
        ),
    ]
